import { readFileSync } from "node:fs";
import { join } from "node:path";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * The service worker, served from a route rather than sat in public/ so its
 * cache name can carry the build id.
 *
 * The old public/sw.js had CACHE_NAME as a hand-edited constant, and the
 * activate handler deletes every cache that is not it — so that one string was
 * both the version marker and the only thing that purges anything, and keeping
 * it correct meant remembering to edit it on every deploy that touched the
 * shell. That is a rule nobody keeps, and the failure is invisible until
 * somebody is offline holding a stale page.
 *
 * Next writes .next/BUILD_ID on every build and it survives into the
 * standalone output, so reading it here makes the cache name change exactly
 * when the assets it caches change. Nothing to remember.
 */
const BUILD_ID = readBuildId();

function readBuildId(): string {
  for (const path of [
    join(process.cwd(), ".next", "BUILD_ID"),
    join(process.cwd(), ".next", "standalone", ".next", "BUILD_ID"),
  ]) {
    try {
      const id = readFileSync(path, "utf8").trim();
      if (id) return id;
    } catch {
      // Try the next location.
    }
  }
  // `next dev` has no BUILD_ID. A per-process value keeps a dev reload from
  // being served yesterday's cache, and never reaches production.
  return `dev-${Date.now()}`;
}

/**
 * Kept as a template string rather than a separate asset so the build id is
 * interpolated once, here, instead of being fetched at runtime by the worker.
 */
function serviceWorkerSource(buildId: string): string {
  return `// Generated by src/app/sw.js/route.ts — do not edit a copy of this.
// Cache name carries the build id, so a deploy purges the old shell
// automatically and no one has to remember to bump anything.
const CACHE_NAME = ${JSON.stringify(`watch-shell-${buildId}`)};

// /downloads is precached deliberately. Everything else caches only when
// visited, and somebody who taps Download on an item page and then loses
// signal may never have opened the downloads screen — which would make the
// one page they need the one page missing.
const PRECACHE_URLS = [
  "/login",
  "/downloads",
  "/manifest.json",
  "/icon-192.png",
  "/icon-512.png",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      // addAll is all-or-nothing, which is what we want: a half-populated
      // cache that then becomes the only source offline is worse than none.
      // If it rejects, activate never runs and the old cache stays serving.
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

// Live state, session state, and video. Caching any of these would either
// serve a stale login or quietly fill the cache with a film — offline
// playback comes from real files on disk, not from here.
const NEVER_CACHE = [/^\\/jf\\//, /^\\/api\\//, /^\\/watch\\//];

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (NEVER_CACHE.some((pattern) => pattern.test(url.pathname))) return;

  // Content-hashed and therefore immutable: a changed chunk has a different
  // URL, so cache-first can never go stale here.
  if (url.pathname.startsWith("/_next/static/")) {
    event.respondWith(
      caches.match(request).then(
        (cached) =>
          cached ||
          fetch(request).then((response) => {
            if (response.ok) {
              const clone = response.clone();
              caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
            }
            return response;
          }),
      ),
    );
    return;
  }

  event.respondWith(
    fetch(request)
      .then((response) => {
        if (response.ok) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
        }
        return response;
      })
      .catch(async () => {
        const cached = await caches.match(request);
        if (cached) return cached;
        // Offline and nothing cached for this exact URL. A navigation should
        // land somewhere useful rather than on a browser error page, and with
        // no network the only useful place is the downloads the device
        // already holds.
        if (request.mode === "navigate") {
          return (await caches.match("/downloads")) || (await caches.match("/login")) ||
            new Response("Offline", { status: 503, headers: { "Content-Type": "text/plain" } });
        }
        return new Response("Offline", { status: 503 });
      }),
  );
});

// The page asks for this when a download starts — the moment somebody has
// declared they intend to be offline. Re-fetching the shell then means the
// downloads screen is definitely cached before it is needed, rather than
// only if they happened to visit it earlier.
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "warm") {
    event.waitUntil(
      caches.open(CACHE_NAME).then((cache) =>
        cache.addAll(PRECACHE_URLS).catch(() => {
          // Warming is best effort; failing it must not break the download
          // that triggered it.
        }),
      ),
    );
  }
});
`;
}

export function GET(): Response {
  return new Response(serviceWorkerSource(BUILD_ID), {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // Lets the worker control the whole origin even though it is served
      // from /sw.js.
      "Service-Worker-Allowed": "/",
      // The browser must notice a new worker promptly; this is the file whose
      // bytes changing is what triggers an update at all.
      "Cache-Control": "no-cache, no-store, must-revalidate",
    },
  });
}
